/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ServicesAgenticSdlcImpactMethodRouteImport } from './routes/services/agentic-sdlc-impact-method'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiImpactInterestRouteImport } from './routes/api/impact-interest'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAgenticSdlcImpactMethodRoute =
  ServicesAgenticSdlcImpactMethodRouteImport.update({
    id: '/services/agentic-sdlc-impact-method',
    path: '/services/agentic-sdlc-impact-method',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImpactInterestRoute = ApiImpactInterestRouteImport.update({
  id: '/api/impact-interest',
  path: '/api/impact-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/api/impact-interest': typeof ApiImpactInterestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/agentic-sdlc-impact-method': typeof ServicesAgenticSdlcImpactMethodRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/api/impact-interest': typeof ApiImpactInterestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/agentic-sdlc-impact-method': typeof ServicesAgenticSdlcImpactMethodRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/contact': typeof ApiContactRoute
  '/api/impact-interest': typeof ApiImpactInterestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/agentic-sdlc-impact-method': typeof ServicesAgenticSdlcImpactMethodRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/contact'
    | '/api/impact-interest'
    | '/blog/$slug'
    | '/services/agentic-sdlc-impact-method'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/contact'
    | '/api/impact-interest'
    | '/blog/$slug'
    | '/services/agentic-sdlc-impact-method'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/api/contact'
    | '/api/impact-interest'
    | '/blog/$slug'
    | '/services/agentic-sdlc-impact-method'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiImpactInterestRoute: typeof ApiImpactInterestRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesAgenticSdlcImpactMethodRoute: typeof ServicesAgenticSdlcImpactMethodRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/agentic-sdlc-impact-method': {
      id: '/services/agentic-sdlc-impact-method'
      path: '/services/agentic-sdlc-impact-method'
      fullPath: '/services/agentic-sdlc-impact-method'
      preLoaderRoute: typeof ServicesAgenticSdlcImpactMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/impact-interest': {
      id: '/api/impact-interest'
      path: '/api/impact-interest'
      fullPath: '/api/impact-interest'
      preLoaderRoute: typeof ApiImpactInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiContactRoute: ApiContactRoute,
  ApiImpactInterestRoute: ApiImpactInterestRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesAgenticSdlcImpactMethodRoute: ServicesAgenticSdlcImpactMethodRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
